name: Deploy

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 147.45.104.2 >> ~/.ssh/known_hosts

      - name: Debug SSH connection
        run: |
          ssh -v root@147.45.104.2 "echo 'SSH connection successful'"

      - name: Deploy to server
        run: |
          ssh root@147.45.104.2 "cd GazAutoService.Web && docker-compose down && git pull origin main && docker-compose up --build -d"
