name: Continuous Integration

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Source code verification
        uses: actions/checkout@v2

      - name: Installing Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Installing dependencies
        run: |
          python -m pip install --upgrade pip
          pip install fastapi uvicorn
          pip install -r requirements.txt

      - name: Uvicorn launch
        run: |
          nohup uvicorn main:app --host 0.0.0.0 --port 8000 & 

      - name: Checking the applications functionality
        run: |
          sleep 10
          curl -f http://localhost:8000/ || exit 1

# FIXME: добавить джобу на сборку докер контейнера